// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7EVmzdNAthoBijr5r1mDMAEWmV_SmdRo',
    appId: '1:619041766707:web:ac612ce45bf84d1f889246',
    messagingSenderId: '619041766707',
    projectId: 'fasum-57450',
    authDomain: 'fasum-57450.firebaseapp.com',
    storageBucket: 'fasum-57450.firebasestorage.app',
    measurementId: 'G-BPK6FTDP1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuY15yES7gThCm1b3GtgDGKzKOrfBrYFY',
    appId: '1:619041766707:android:7aca077f5c01ce8a889246',
    messagingSenderId: '619041766707',
    projectId: 'fasum-57450',
    storageBucket: 'fasum-57450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYoyf8nO5vHhI4sr9rkPDVMjd5JVf4JAg',
    appId: '1:619041766707:ios:bd832bbfe5fc3873889246',
    messagingSenderId: '619041766707',
    projectId: 'fasum-57450',
    storageBucket: 'fasum-57450.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYoyf8nO5vHhI4sr9rkPDVMjd5JVf4JAg',
    appId: '1:619041766707:ios:bd832bbfe5fc3873889246',
    messagingSenderId: '619041766707',
    projectId: 'fasum-57450',
    storageBucket: 'fasum-57450.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7EVmzdNAthoBijr5r1mDMAEWmV_SmdRo',
    appId: '1:619041766707:web:cc4c6a49703d02d3889246',
    messagingSenderId: '619041766707',
    projectId: 'fasum-57450',
    authDomain: 'fasum-57450.firebaseapp.com',
    storageBucket: 'fasum-57450.firebasestorage.app',
    measurementId: 'G-FBRL3G1BRF',
  );
}
